<a href="https://colab.research.google.com/github/CodeParlance/PyLabs/blob/main/LibsPy01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Algoritmos com Python, para Iniciantes #

## Bibliotecas/Módulos Fundamentais ##



## 1. Uma visão genérica de módulos do Python ##

Sempre que estudamos uma linguagem de programação, precisamos dela para resolver
problemas com um interesse específico. Por exemplo, você pode estar interessado
em estatística da qualidade, métodos dos elementos finitos, mecânica dos fluidos
ou hidráulica, ergonomia, etc. Cada uma dessas áreas têm problemas específicos e
isso significa que os profissionais estudam objetos e métodos mais relacionados
com os problemas que querem resolver.

Em programação acontece o mesmo. Para cada necessidade específica é necessário
buscar um módulo ou biblioteca, onde o conhecimento especializado para resolver
uma 'classe de problemas' esteja ali, numa biblioteca ou módulo. Nessa seção nos
interessa apenas os módulos matemáticos ou numéricos que usamos para nossos cál
culos diários manipulando funções, recursos e métodos úteis.

Aqui vamos abordar alguns dos recursos disponíveis em python e que podem ser
acessados em sua documentação na referência: https://docs.python.org/pt-br/3/library/numeric.html

Em Python, os módulos são conjuntos de objetos e métodos que podemos chamar
ou invocar quando precisamos através de declarações no código como segue:

In [ ]:
# carregando a biblioteca/módulo de objetos matemáticos de maneira geral
import math


A linha acima dar a instrução ao python para carregar todos os objetos da biblioteca matemática. Para saber quais são esses objetos, de forma abrangente, consulte a documentação do python em: https://docs.python.org/pt-br/3/library/math.html#module-math

In [ ]:
Todavia, em geral não precisamos carregar de uma vez só todos os objetos, podemos
especificar quais aqueles que iremos utilizar na resolução de um problema. 
Por exemplo


In [ ]:
# carrega a função raiz quadrada do módulo math
from math import sqrt
num = 1024
raiz = sqrt(num)
print(raiz)

32.0


In [ ]:
# Outra forma seria ...
import math
num = 35
# modulo.método
math.sqrt(num)



5.916079783099616

In [ ]:
# Uma outra maneira válida ...
import math as mt
num = 9
mt.sqrt(num)

3.0

In [ ]:
# uma forma mais geral, para importar todos os objetos num módulo
from math import *
num = 9
angulo = pi/2
calcule = (sqrt(num))*sin(angulo)*exp(-1)
print(round(calcule,5))

1.10364


No cálculo acima, note que usamos vários objetos da biblioteca matemática do python, tais
como o 'pi', a função seno 'sin', a função exponencial 'exp' e a função raiz quadrada 
'sqrt'. Poderíamos usar qualquer outra da vasta biblioteca 'math' do python.

## 2. A Biblioteca 'math' do Python. ##

Embora o python tenha de forma nativa muitas funcionalidades matemáticas, por exemplo a função de arredondamento 'round' é nativa do Python, ou seja não precisamos chamar nenhum módulo para usá-la.

In [ ]:
# a função 'round' arredonda para um certo número de casas decimais, qualquer número 
# fracionário

num = 3**(1/2)
print(num)
# arredondamento para três casas decimais
print(round(num,5))

1.7320508075688772
1.73205


Todavia uma função para simplesmente truncar a parte inteira da francionária, não
está disponível nativamente no Python, mas está disponível na biblioteca 'math',
logo para usá-la temos que chamar esse módulo (ou biblioteca)...

In [ ]:
# calcula a raiz de 2, trunca a parte fracionária e imprime a inteira
import math as mt
num = mt.sqrt(3)
print(round(num,3))
print(trunc(num))

1.732
1


### 2.1 Constantes Fundamentais ###

Que tal apresentar o número pi e o número de euler em Python. Veja o código a seguir...

In [ ]:
import math as mt
num1 = mt.pi
num2 = mt.e
print(round(num1,10))
print(round(num2,10))



3.1415926536
2.7182818285


### 2.2 Ângulos: Graus e Radianos ###

Antes de apresentarmos as funções trigonométricas existentes na 'math' library (biblioteca)
vamos tratar ângulos em python, usando o módulo 'math'...

In [ ]:
# Convertendo de radianos para graus
import math as mt
emRadianos = round(pi/4,2)
emGraus=round(mt.degrees(emRadianos),2)
print(emRadianos, "radianos expresso em graus fica: ~", emGraus)
# Convertendo de graus para radianos
emGraus_1 = 90
emRadianos_1 = round(mt.radians(emGraus_1),2)
print(emGraus_1, "graus expresso em radianos fica: ~", emRadianos_1)

0.79 radianos expresso em graus fica: ~ 45.26
90 graus expresso em radianos fica: ~ 1.57


Nunca será demais lembrar que as funções trigonométricas em python trabalham com radianos e portanto a conversão é necessária sempre que você preferir trabalhar com graus.

### Senos, cossenos e tangentes ###

'Math' dispõe de todas as funções trigonométricas clássicas, bem como as hiperbólicas
também, vejamos alguns exemplos...

In [ ]:
# Calculando senos e cossenos
import math as mt
rads1=pi/2
seno90 = mt.sin(rads1)
rads2=0
cos0 = mt.cos(rads2)
print("Seno de", rads1, "é:", seno90)
print("Cosseno de", rads2, "é:", cos0)

Seno de 1.5707963267948966 é: 1.0
Cosseno de 0 é: 1.0


In [ ]:
# Calculando tangentes

import math as mt
# angulos em radianos
ang45 = pi/4
ang60 = pi/3
# chama tangentes em math
tan60 = mt.tan(ang60)
tan45 = mt.tan(ang45)
# imprime valores das tangentes nos arcos dados
print(round(tan45,2))
print(round(tan60,2))

1.0
1.73


Tente fazer alguns cálculos semelhantes e explore também as outras funções trignométricas
tais como arco seno 'asin', arco cosseno 'acos' e arco tangente 'atan'.

Além dessas, explore as funções hiperbólicas dadas  em: https://docs.python.org/pt-br/3/library/math.html#trigonometric-functions

### 2.3 Funções Potência e Logaritmos ###

E quando precisamos lidar com exponenciações e logaritmos a biblioteca 'math' também nos auxilia muito com diversas funções úteis para os nossos cálculos, vejamos exemplos...

In [ ]:
ax = 3**2
print(ax)

9


In [ ]:
# função potência
import math as mt
expo=3
base=2
# power abreviado vira pow
res=mt.pow(base,expo)
print(res)
# função exponencial exp(x)
num_euler=mt.exp(1)
print(num_euler)
# função logaritmo natural ln = log (x)
# log(x,base). Base omitida significa base = num_euler
out1 = log(e)
print(out1)
# log(x,base). Com base definida, por exemplo base = 10
out2 = log(2,10)
print(out2)
# especificamente, temos o log10(x), log de x, na base 10
out3 = log10(2)
print(out3)


8.0
2.718281828459045
1.0
0.30102999566398114
0.3010299956639812


### 2.4 Outras funções úteis ###

Há inúmeras outras funções na lib math, mas é claro que métodos ou funções numa biblioteca só são úteis quando precisam ser utilizadas. Algumas outras funções
desta biblioteca que aparecem com frequência em nossos cálculos são vistas no código abaixo:





In [5]:
# a função fatorial - calculando para 1 a 50
import math as mt
for i in range(51):
    print("O fatorial de", i, "é", mt.factorial(i))

O fatorial de 0 é 1
O fatorial de 1 é 1
O fatorial de 2 é 2
O fatorial de 3 é 6
O fatorial de 4 é 24
O fatorial de 5 é 120
O fatorial de 6 é 720
O fatorial de 7 é 5040
O fatorial de 8 é 40320
O fatorial de 9 é 362880
O fatorial de 10 é 3628800
O fatorial de 11 é 39916800
O fatorial de 12 é 479001600
O fatorial de 13 é 6227020800
O fatorial de 14 é 87178291200
O fatorial de 15 é 1307674368000
O fatorial de 16 é 20922789888000
O fatorial de 17 é 355687428096000
O fatorial de 18 é 6402373705728000
O fatorial de 19 é 121645100408832000
O fatorial de 20 é 2432902008176640000
O fatorial de 21 é 51090942171709440000
O fatorial de 22 é 1124000727777607680000
O fatorial de 23 é 25852016738884976640000
O fatorial de 24 é 620448401733239439360000
O fatorial de 25 é 15511210043330985984000000
O fatorial de 26 é 403291461126605635584000000
O fatorial de 27 é 10888869450418352160768000000
O fatorial de 28 é 304888344611713860501504000000
O fatorial de 29 é 8841761993739701954543616000000
O fatorial 

In [ ]:
# para calcular combinações (sem ordem e sem repetição) de n elementos k organizados
# comb(n,k)= n!/(k! * (n - k)!) temos
import math as mt
n1 = 10
k1 = 3
comb1 = mt.comb(n1,k1)
print(comb1)

120


In [ ]:
# calculando o piso de x, com floor(x), ou seja o maior inteiro que não supera x
import math as mt
pisox = mt.floor(3.6)
# calculando o teto de x, com ceil(x), ou seja o menor inteiro que supera x
tetox = mt.ceil(3.6)
print(pisox)
print(tetox)
# calculando o valor absoluto de um num
num = -2.33
print(fabs(num))

3
4
2.33


In [ ]:
###2.5 Funções matemáticas para números complexos ###

A biblioteca 'math' possuem um módulo análogo para manipulação de operações com números
complexos: é a biblioteca 'cmath'. 
ver https://docs.python.org/pt-br/3/library/cmath.html#module-cmath

Números complexos em pytho são definidos pela sua *parte real a*, *parte imaginária b* e
o *formato z = a + bj*, logo temos códigos tais que:

In [ ]:
# carga da cmath
import cmath as mc
print(mc.sqrt(-9)) # calculando raiz de número negativo
#
z = 4 - 2j  # definindo um complexo por extensão
#
print(z.real) # recupeando a parte real
print(z.imag) # recuperando a parte imaginária
#
zp=complex(2,2) # definindo um complexo
print(zp)
## e^i*pi + 1 = 0
xp = mc.exp(1j*pi) # cálculo de e^(i*pi) ~ -1
print(xp)


3j
4.0
-2.0
(2+2j)
(-1+1.2246467991473532e-16j)


## 3 . A biblioteca de números aleatórios random ##

### 3.1 Porquê números aleatórios? ###

Em problemas de engenharia, como noutras áreas, necessitamos fazer experimentos com base
em dados. Muitas vezes não temos acesso direto aos dados, mas sabemos algo sobre o 
comportamento deles e nesse caso podemos simular tais dados e fazer uso deles em nossos
cálculos. Você saberá mais sobre isso após estudar estatística e probabilidades, por hora
nosso interesse nesses números é na possibilidade de gerá-los em computador.

### 3.2 Geradores de números aleatórios ###

Já imaginou o que acontece com, digamos, o seu aplicativo do spotify, dizzer ou amazon music
quando você acionar o modo de escolha aleatória de músicas numa playlist? Agora você vai 
descobrir a matemática por trás disso.

In [ ]:
import random as rd
for i in range(10):
 print (rd.randint(0,100))

58
97
53
60
62
66
87
99
7
85


In [ ]:
# gerando números aleatórios em python
import random as rd

def EscolhaMusica(SuaLista):
 Lista = SuaLista
 escolha = rd.randint(0,len(Lista)-1)
 return(Lista[escolha])

# Defina sua lista preferida
# a \ indica uma quebra de linha na declaração e continuação 
# na linha seguinte ...

playList = ["Sina/Djavan", "Rolling in the Deep/Adele", \
            "Talking to the moon/Bruno Mars", \
            "Faded/Alan Walker", "The Scientist/ColdPlay", \
            "All of Me/Jonh Legend", "New Rules/Dua Lipa"]
  
# Execute ordem aleatória
print(len(playList))
print(EscolhaMusica(playList))


7
New Rules/Dua Lipa


O algoritmo acima, recebe uma lista com uma playList bem curta, preferida de alguém por aí. O algoritmo
chama a biblioteca random, para lhe ajudar a gerar números aleatórios que apontem para os índices da 
lista que possuem uma música, de seu respectivo compositor/intérprete, gerando escolhas diferentes
sempre que é solicitado a fazer isso. A base disso é uma distribuição de probabilidades uniforme (ou seja, escolhas com mesma probabilidade) que é representada no algoritmo pela **função 'randint'**.

Observe que chamamos randint no intervalo [0, N - 1], onde N é o tamanho da playlist. Ou seja, randint vai escolher qualquer música, com a mesma probabilidade sempre que for chamada.

Para experimentar, tente executar várias vezes o código acima e observe o resultado obtido em seu experimento aleatório.

Mas, em que pese o experimento acima ter lhe dado uma boa ideia de utilização de números aleatórios, 
vamos apelar um pouco mais para o seu senso acadêmico. Quando estudamos probabilidades é comum falar
sobre lançamentos de moedas como experimentos aleatórios que lhe ajudam a compreender probabilidades,
suponha que seu professor de estatística solicite que você faça um experimento estatístico lançando
10.000 vezes uma moeda honesta (isto é, não viciada) e observe a frequência a face de cima. Quais as
frequências obtidas por cara e coroa?

A questão para você é como realizar esse experimento. Talvez seja inviável para você e seus amigos
passarem um dia inteiro lançando moedas ao acaso e anotando o resultado da face de cima, mas como
você sabe programar em python, tudo fica mais simples e você vai propor ao seu professor uma simulação
estatística, usando um modelo computacional. Vejamos como...

In [1]:
# lançamento de moedas
import random as rd
moeda = ['cara', 'coroa']   # espaço amostral
conteCara = 0               # frequencia de caras
conteCoroa = 0              # frequência de coroas
num_lanc = 10000
for i in range(num_lanc):      # repetir o experimento 10 mil vezes
    faceObservada = moeda[rd.randint(0,1)] # observar a face de cima
    if faceObservada == 'cara':            # verificar se foi cara e contar
       conteCara = conteCara + 1
    else:                                  # se foi coroa, contar também
        conteCoroa = conteCoroa + 1
print("Resultado do Experimento Aleatório\n")  # publique os resultados encontrados
print("Frequencia de cara: ", conteCara, "\n")
print("Frequencia de coroa: ", conteCoroa, "\n")

    

Resultado do Experimento Aleatório

Frequencia de cara:  5052 

Frequencia de coroa:  4948 



Pois é, você acabou de realizar seu primeiro experimento de simulação computacional com o auxílio luxuoso
da biblioteca **random**. Observe que usamos o método randint no exemplo acima, **randint(ini,fim)** é uma função que gera números aleatórios no intervalo dado por ini e fim. No exemplo acima, o valor devolvido por randint é 0 ou 1, ou seja é o índice que indica se a face da moeda é cara ou coroa, a cada lançamento.

Um outro comando bastante útil em simulações e geração de amostras aleatórias sem repetição é o comando
'sample' da biblioteca random. Abaixo criamos uma faixa de 25 valores e em seguida sorteamos 15 desses 
números numa amostra

In [ ]:
import random as rd
sorteio=rd.sample(range(1,26),15)
print(sorteio)

[24, 5, 2, 17, 14, 22, 3, 16, 13, 7, 4, 11, 1, 8, 10]


No código a seguir geramos várias dessas amostras ao executarmos uma repetição na geração das amostras
aleatórias...

In [ ]:
import random as rd
n=5
for i in range(n+1):
 sorteio=rd.sample(range(1,26),15)
 print(sorteio)
 print('\n')

[24, 16, 1, 21, 22, 18, 2, 9, 25, 23, 4, 10, 20, 17, 7]


[17, 22, 10, 20, 11, 18, 14, 23, 19, 12, 15, 3, 1, 16, 25]


[21, 8, 7, 12, 15, 2, 13, 16, 14, 20, 25, 18, 23, 22, 3]


[24, 5, 20, 7, 10, 8, 23, 22, 25, 16, 21, 12, 3, 19, 1]


[15, 9, 21, 6, 10, 13, 24, 4, 1, 14, 7, 16, 5, 22, 8]


[13, 25, 22, 7, 14, 21, 17, 15, 10, 1, 23, 11, 3, 24, 9]




Vamos avançar um pouco mais. Suponha que por alguma necessidade (criação de vetores aleatórios, por exemplo) você tenha que inicializar um vetor de 10 dimensões com números no intervalo [0,1], mas 
definindo uma precisão de apenas 4 casas decimais. Como podemos fazer isso em Python, com os conhecimentos vistos até aqui?


In [ ]:
# Vetor aleatório de dimensão 10
import random as rd                           # importar random
vt_alea = []                                  # uma lista vazia
for nx in range(10):                          # repetindo 10 vezes o processo
    vt_alea.append(round(rd.random(),4))      # gerar um aleatório em 0,1 e arrendondar 4 casas
print(vt_alea)                                # imprimir lista gerada
    

[0.3348, 0.4121, 0.424, 0.8776, 0.8233, 0.6298, 0.4452, 0.9332, 0.3963, 0.6114]


Quando geramos números aleatórios outras funções presentes em 'random' podem ser importantes. Por exemplo,
como os resultados gerados por random são (pretensamente) aleatórios, sempre que você repete aquele experimento vai obter resultados diferentes do anterior. É o que se espera, que 'jamais' se repitam.

Pense num situação onde você quer replicar um experimento. Ou seja, apesar do experimento ser aleatório vc
gostaria que seus colegas possam obter os mesmos resultados numa replicação daquele experimento. Felizmente,números aleatórios não são *totalmente aleatórios* quando gerados por computador, por isso chamamos esses números de pseudo-aleatórios, pois são gerados por alguma 'regra computacional' ou 'fórmula matemática' que seguem leis probabilísticas e portanto comportam-se como se fosse 'totalmente aleatórios'.

Uma das propriedades dos pseudo-aleatórios é possuírem um *número-semente*, ou seja, uma raiz geradora 
desses números, de tal sorte que a partir da mesma 'semente' (seed em inglês). 

No código abaixo, vamos iniciar o nosso algoritmo com uma semente. Um número semente é um natural 
qualquer que você 'amarra' no início do seu experimento, para que outras pessoas que repitam seu
experimento possam obter os mesmos resultados que você ao replicarem a sua simulação computacional.
No caso abaixo escolhemos o número '1966' com semente do nosso experimento, poderíamos escolher
qualquer outro número para 'amarrar' ao nosso experimento 'aleatório'. Esse número vai garantir
que nas mesmas condições estatísticas e computacionais, o experimento aleatório realizado dará 
os mesmos resultados. Vejamos o código...

In [ ]:
# 
import random as rd  # chame a biblioteca random 
rd.seed(2022)         # inicia uma semente. 
print(rd.random())

0.531625749833213


Tente executar o código acima várias vezes, com e sem o número semente. Tente outras vezes mudando o número
semente e verifique o que acontece.

Para fechar momentaneamente nosso interesse em algumas funções do módulo random, vejamos algumas outras
funções dessa lib que poderão ser úteis em exercícios ou trabalhos futuros.

Uma das funções que usamos para escolher elementos de forma aleatória, num vetor, numa lista ou noutro 
objeto qualquer é a random.choice e o que ela faz é melhor explicada com o código a seguir...

In [ ]:
import random as rd
estado = ['tracionado', 'tensionado', 'defletido', 'normal']
rotação=rd.choice(estado)
print(rotação)

normal


No código acima submetemos um corpo a um movimento rígido de rotação, mas sobre o corpo atuam outras
forças, de tal forma que nosso 'sólido' pode assumir os quatro estados representados naquela lista.
Supondo que os estados são aleatórios, queremos representar um experimento onde rotacionamos o corpo
e observamos em que estado ele vai se encontrar após a rotação. Os estados são igualmente prováveis.

Observe que no contexto do problema o que 'choice' nos dá é um processo de escolha aleatória dos
estados em que o corpo poderá se encontrar. Um bom exercício é você verificar o que acontece 
quando esse experimento se repetir 1.000 vezes, tente checar a frequência de cada estado e faça
cálculos sobre a probabilidade de o corpo se encontrar em um certo estado (digamos, normal)
após 10.000 rotações. Observe que nesse instante você estará 'aprendendo a lidar' com situações
de incerteza e a 'simular tais condições', através de modelos computacionais.

### 3.3. 'Randomness'. Conversando sobre aleatoriedade, engenharias e simulações computacionais ###

'At random' em inglês, em livre tradução para o português, significa 'ao acaso'. Então estamos aprendendo
a lidar com as 'leis do acaso', ou seja - entramos no mundos das probabilidades - onde cientistas e 
engenheiros procuram entender o comportamento de variáveis ditas aleatórias. Variáveis cujos comportamentos
estão longe de serem determinísticos. Na verdade esse é um mundo onde o indeterminismo governa os processos.

Para entender o acaso é preciso entender probabilidades e para simular o acaso é preciso entender o 
comportamento dos processos aleatórios, compreendendo a relação entre suas variáveis. Felizmente isso
é possível graças a teoria das probabilidades e também a inferência estatística. Mas aqui estamos
apenas interessados como podemos usar computação para experimentar, simular e fazer 'contas' com esses
processos.

Quando prédios desabam, pontes caem ou produtos defeituosos são entregues ao consumidor - algo de errado 
com os processos de engenharia, ocorreu - invarialmente riscos deixaram de ser calculados ou foram 
abordados de forma errada. Muito provavelmente análises estatísticas e computacionais deixaram de ser
realizadas, além de prováveis falhas humanas. De uma forma ou de outra - a aleatoriedade está envolvida.

Na estatística básica, estudantes de engenharia, tecnologias e de ciências aprenderão a lidar com situações de incerteza
conhencendo algumas das principais variáveis aleatórias, ensinadas como 'distribuições de probabilidade'.

Elas serão conhecidas por definirem um comportamento governado pelo acaso, mas as chances de ocorrência
dos valores dessas variáveis serão conhecidos, uma vez conhecida como as chances de ocorrência de cada
valor de variável (ou característica) estão definidas por sua função de probabilidades. A grosso modo, saberemos as chances de uma determinada variável
assumir um certo valor e com base nisso poderemos fazer previsões (ou projeções) sobre o comportamento
futuro de um determinado processo ou de um material. 

Por exemplo poderemos prever quando e se uma máquina recém adquirida para uma fábrica poderá produzir lotes
defeituosos ou se em determinadas regiões de venda qual o percentual de consumidores satisfeitos, qual a 
chance de uma certa estrutura predial sofrer rápida fadiga e depreciação, em função de vibrações esporádicas
causadas pela presença de uma linha férrea nas proximidades, ou por mudanças na porosidade do solo
após sucessivas enchentes. Enfim, processos aleatórios acontecem o tempo todo alterando as condições
iniciais, introduzindo erros e variâncias, exigindo pelo menos uma 'análise de sensibilidade' em nossas
contas ou uma completa revisão do nosso 'modelo' matemático sobre 'estruturas' ou 'processos'.

#### 3.3.1 Introdução básica à computação de variáveis aleatórias  ####

Começamos essas seção como um 'longo papo' sobre aleatoriedade e como ela está presente em nossas
vidas, principalmente no comando do 'acaso'. Nas engenharias, como nas ciências, sabemos que ela
(lady randomness, ou lady Alea - para os íntimos) atua bastante e é responsável pela complexidade
de muitos modelos naturais ou artificiais. 

Nesta seção veremos alguns modelos computacionais de variáveis aleatórias que aparecem nos livros
de estatística e probabilidade para engenheiros e cientistas, principalmente por sua importância
na compreensão e experimentação dos fenômenos com os quais lidamos.

#### 3.3.2 A distribuição uniforme ####

Em linguagem matemática, dado um intervalo $(a,b)$ - se $f$ é uma distribuição de probabilidade naquela intervalo
então $f$ é dita distribuição uniforme de probabilidade se e só se:

\begin{align}
	\textbf{Distribuição Uniforme f} \\
	\textbf{f(x) = } 
	\begin{cases} 
	  \frac{1}{b - a}, & a\leq x\leq b\\
      0, &  x \notin [a,b]
    \end{cases}
\end{align}
    

Observe que sendo $f(x)$ uma probabilidade, ela está definida no intervalo $[0,1]$, todavia a probabilidade 
de ocorrer (ou de sortearmos) qualquer ponto num intervalo $[a,b]$ é proporcional ao tamanho desse intervalo
e, obviamente, qualquer ponto fora desse intervalo é 'sorteado' com probabilidade zero. A média para essa 
distribuição é dada por $\frac{b+a}{2}$.

Em python, podemos gerar números aleatórios que seguem uma probabilidade uniforme (ou seja, se comportam de acordo
de acordo com essa função) da seguinte forma...

In [2]:
# gerando números aleatórios conforme a distribuição uniforme
import random as rd
pA = 1
pB = 5
rd.uniform(pA, pB)

2.1179252517367986

Exercício resolvido. Aplicação de números aleatórios a geração de amostras. Distribuição uniforme.

Verificou-se que num determinado equipamento de precisão os erros medidos na faixa de valores entre **10.50mm e 10.90mm** ocorrem com a mesma probabilidade. Foram feitas 50 medidas ao acaso. Simule em computador as medidas e calcule a média dos resultados obtidos (na amostra gerada) e compare com a média teórica da distribuição. A precisão das medidas é fixada em 2 casas decimais.

In [3]:
# o modelo segue uma distribuição uniforme, mas precisamos gerar 50 números aleatórios 
# com a característica seguindo a distribuição 'uniforme' ...
import random as rd
# se quiser amarra a simulação e replicar o resultado, descomente abaixo
# rd.seed(1010)
## condições iniciais do experimento e definições - preprocessamento -> entrada# 
quant_medidas = 50
lista_med = []
limite_a=10.50
limite_b=10.90
## neste bloco, fazemos a simulação das medições conforme o problema enuncia - processamento
for medições in range(quant_medidas):
    lista_med.append(round(rd.uniform(limite_a,limite_b),2))

## ora de organizar os resultados - pós-processamento -> saída
print("A simulação das medidas (amostra gerada):")
print("-----------------------------------------")
print(lista_med)
print("------------------------")
print("A média calculada foi:")
print("------------------------")
media=round(sum(lista_med)/len(lista_med),2)
print("média obtida na amostra: ", media)
med_teorica = round((limite_b + limite_a)/2,3)
print("média teórica: ", med_teorica)


A simulação das medidas (amostra gerada):
-----------------------------------------
[10.56, 10.51, 10.73, 10.55, 10.76, 10.57, 10.84, 10.85, 10.76, 10.78, 10.74, 10.8, 10.52, 10.51, 10.59, 10.66, 10.85, 10.53, 10.57, 10.6, 10.59, 10.6, 10.78, 10.76, 10.51, 10.54, 10.67, 10.69, 10.83, 10.61, 10.68, 10.8, 10.53, 10.71, 10.69, 10.71, 10.77, 10.6, 10.67, 10.72, 10.84, 10.75, 10.65, 10.68, 10.72, 10.55, 10.88, 10.68, 10.61, 10.57]
------------------------
A média calculada foi:
------------------------
média obtida na amostra:  10.67
média teórica:  10.7


Outra importante distribuição (de probabilidades) é a gaussiana, popularmente conhecida como curva normal 
de Gauss. Talvez a mais importante distribuição de toda estatística (pela quantidade de aplicações e pela
presença no comportamento de fenômenos naturais) seja a gaussiana. Os alunos de engenharia e ciÊncias que
estudam estatística certamente terão o prazer de estudá-la e perceber sua grande utilidade dentro de 
inúmeras áreas na engenharia, nas ciências e na computação.

Variáveis aleatórias aparecem em muitas bibliotecas em Python, mas na lib 'random' aparecem de maneira
bastante sutil e com apelo para geração de números aleatórios de forma rápida e prática.

A função random.gauss toma dois parâmetros a média $\mu$ e o desvio padrão $\rho$. Assim, para chamá-la
precisamos ter uma média 'med' definida e o desvio padrão 'std' dado, logo random.gauss(med, std) computa
um número aleatório que segue a distribuição gaussiana com esses parâmetros. Vejamos um exemplo.

Numa determinada população, a altura de adultos, homens e mulheres, seguem a distriuição de Gauss. Sabe-se que a
média das alturas é 175 cm com desvio-padrão de 25 cm. Gere 10 amostras aleatórias de 100 indivíduos, cada, nessa população e calcule suas alturas. Compare a média das amostras, com a média da população.

In [4]:
import random as rd
# parâmetros da curva de Gauss
media = 175
desvio = 25
# parâmetros do experimento de amostragem
num_levantamentos = 2
num_indivíduos = 10
# execução da simulação
for i in range(num_levantamentos):
    amostra = []
    for j in range(num_indivíduos):
      amostra.append(round(rd.gauss(media, desvio),0))
    medx = sum(amostra)/len(amostra)
    ## pós-processamento  a cada levantamento índice i
    print("------------------------")
    print("A amostra",i+1,"gerada, foi:")
    print("------------------------")
    print(amostra,"\n")
    print(">> a média da amostra", i+1, "foi: ", medx, "e a média da população é: ", media, "<<\n")

------------------------
A amostra 1 gerada, foi:
------------------------
[197.0, 209.0, 166.0, 202.0, 174.0, 192.0, 127.0, 219.0, 174.0, 175.0] 

>> a média da amostra 1 foi:  183.5 e a média da população é:  175 <<

------------------------
A amostra 2 gerada, foi:
------------------------
[136.0, 189.0, 192.0, 208.0, 148.0, 160.0, 97.0, 192.0, 116.0, 152.0] 

>> a média da amostra 2 foi:  159.0 e a média da população é:  175 <<



Sugiro que você melhore alguns aspectos da simulação acima e observe o que acontece. Mesmo que você ainda não
tenha feito um curso de estatística, procure descobrir o que está acontecendo, em termos das leis das
probabilidade. Por exemplo, experimente um pouco e aumente o **num_levantamentos para 10** e o **num_indivíduos
por amostra para 100**, experimente outros números maiores e veja o que acontece, quando você compara a
média das amostras com a da população.

## 4. A Biblioteca de Processamento Numérico 'NumPy' ##

Indubitalvemente, precisamos lidar com matrizes e vetores em qualquer área da ciência e das engenharias. 
Vetores, matrizes e até suas generalizações - os tensores, são objetos fundamentais na computação, na astronomia,
na física ou na construção civil. Lidamos o tempo inteiro com abstrações numéricas conhecidas como
espaços vetoriais e seus objetos, os vetores. 

Na maioria das vezes nossos problemas são expressos como operações sobre vetores, usando cálculo diferencial e integral para medir grandezas físicas descritas como vetores. Indo pouco mais além, a própria álgebra linear
é o fundamento matemático para muitas das aplicações modernas na computação e nas engenharias, como por exemplo
os modelos de computação e expressão gráfica e a própria inteligência artificial (I.A.), por exemplo, as redes de neurônios artificiais (ou redes neurais, como chamamos na I.A.). 

O cálculo numérico é uma disciplina de apoio às engenharias. É o estudo de métodos matemáticos analíticos, com
ênfase em técnicas de solução numérica para permitir soluções computacionais ou seja, algoritmos, que auxiliem
na solução de problemas complexos - como soluções de sistemas de equações, aproximações de séries e sequências
numéricas, busca de soluções de equações diferenciais ordinárias ou parciais, otimização de funções e também
ajuda. Em Python, a biblioteca 'NumPy', nos fornece um conjunto de objetos que auxiliam no processamento
numérico de vetores e matrizes, além de outras funções matemáticas úteis em nossos cálculos.

### Introdução a biblioteca (ou módulo) 'NumPy' ###



In [ ]:
import numpy as np

O código acima refer-se a maneira como costumamos chamar o módulo numpy antes de escrevermos nossos algoritmos,
programas ou pacotes inteiros com soluções para os nossos problemas - ou simplesmente um pedaço de código (snippet) que executa alguma tarefa que precisamos resolver usando Python.

Por exemplo, veja o sistema de equações lineares descrito abaixo:


\begin{align} \label{eq:sistema01}
	\text{Sistema de Equações:}
	\begin{cases} 
		3x_1 - 2x_2 + 1x_3 = 11\\
		-2x_1 + 3x_2 -3x_3 = -19\\
		-x_1 - 3x_2 - 4x_4 = -15
	\end{cases}	
\end{align}

Como podemos usar o Python para resolvê-lo e como a biblioteca 'NumPy' pode nos ajudar nessa missão? Temos então
duas importantes questões: (a) Como representar matrizes e vetores com 'NumPy' e (b) se temos algum 'método numérico' disponível em 'NumPy' que possamos aplicar para resolver o sistema de equações lineares, sem precisar fazer isso 'na mão', já que dispomos de computador e eles são feitos para isso mesmo: computar, enquanto pensamos.

Vamos começar respondendo a perguntar (a) ou seja: Como representar matrizes e vetores com NumPy? Um aluno atento
poderia sugerir que as listas do Python poderiam servir como uma boa estrutura de dados para 'acomodar' um vetor
ou, por assim dizer, n linhas de uma matriz de m colunas e, claro, considerando apenas o aspecto de 'representação' ou 'descrição' da matriz, sem dúvida seria uma boa ideia, todavia do ponto de vista de operações
ou métodos associados a uma matriz, pode-se demonstrar que não é muito eficiente computacionalmente.

A saída oferecida por NumPy é um objeto matemático que generaliza matrizes e vetores, chamado 'Array'. Na língua inglesa o termo 'array' pode designar muitas coisas, mas nesse contexto matemático ele está relacionado a coleções de tabelas ou simplesmente a ideia de agrupamento. Então ao tentar entender um 'array' como estrutura
simplesmente enxergue-o como um 'organizador' onde você possa guardar, organizar e agrupar objetos matemáticos
que se assemelhem a vetores ou matrizes, ou ainda múltiplas coleções desses tipos de dados. Entendida a noção
de 'array' vamos começar a fazer uso deles.

In [ ]:
import numpy as np
print(np.__version__)

1.20.3


Acima chamamos a biblioteca numpy e verificamos sua versão. A última versão de dezembro de 2021 é a 1.21. Sempre
é bom trabalhar com 'releases' ou versões de bibliotecas atualizadas ou bem próximas da atual. Neste caso estamos
contemplados. Vamos prosseguir

In [ ]:
# criando um vetor de 4 dimensões, numa estrutura de array da np (apelido da numpy) 
vetA = np.array([0,-2,1,1])
print(vetA)

[ 0 -2  1  1]


In [ ]:
# vamos checar qual é o tipo de dado da estrutura criada
type(vetA)

numpy.ndarray

Observe que o Python retorna o tipo 'ndarray'. É assim que o Python reconhece internamente as estruturas de array
criadas em NumPy.

In [ ]:
Arrays também possuem dimensões, assim como vetores e matrizes. Podemos ter arrays com dimensões 0,1,2,3 e assim 
por diante. Uma forma de se obter a dimensão de um 'array' é:

In [ ]:
# o método ndim é aplicado num array para saber sua dimensão n.
# no caso vetores são linhas ou colunas, sendo vistas como variedades de dimensão 1, pelos arrays.
vetA.ndim

1

In [ ]:
# criando um ponto numa reta, ou seja, um escalar (real qualquer).
escalarX = np.array(0)
print(escalarX)

0


In [ ]:
# um ponto tem dimensão zero, logo ndim aplicado ao array é: 
escalarX.ndim

0

In [ ]:
E o que conterá os arrays de dimensões dois? Hora de descobrir essas estruturas no código abaixo:

In [ ]:
# criando matrizes, organizadas em arrays
matrizMA = np.array([[1,-2,-1,0], [2,1,-1,5], [1,1,0,-1]])
print(matrizMA)
# matrizes são tabelas, variedades planares, logo sua dimensão de objeto (planar) é um array de ordem dois.
matrizMA.ndim
###


[[ 1 -2 -1  0]
 [ 2  1 -1  5]
 [ 1  1  0 -1]]


2

Não confunda a dimensão do array, com a dimensão do objeto que ele criou. No código acima temos uma matriz de 
ordem 3 x 4, criada como um array de dimensão 2 (variedade matricial).

In [ ]:
Adiante começaremos a fazer operações com arrays, mas por hora ainda precisamos saber como 'acessar' objetos num 
array...por exemplo criamos o vetA e queremos acessar o segundo elemento naquele vetor, como faremos?

In [ ]:
#lembrando que o python começa a indexar objetos a partir de n = 0, logo o segundo elemento é o n = 1
vetA[1]

-2

In [ ]:
E como acessar em matrizMA o elemento na terceira linha e terceira coluna?

In [ ]:
#  i,j será  3 - 1, 3 - 1 = 2,2  --> não esquecer que o python indexa a partir do 0 e não do 1!
matrizMA[2,2]

0

Como vimos os arrays podem ser usados para definir objetos matemáticos como vetores e matrizes, ou objetos mais
gerais chamados de 'tensores' (por exemplo, objetos que tenham linhas, colunas e profundidades - uma 'matriz' 
espacial, por assim dizer)

In [ ]:
# criando um vetor de 4 dimensões, numa estrutura de array da np (apelido da numpy) 
vetA = np.array([1,-1,0,1])
print(vetA)

[ 1 -1  0  1]


numpy.ndarray

Passamos agora a responder a pergunta em (b): existe alguma forma de resolver o sistema de equações lineares dado, com o apoio da biblioteca NumPy? Vamos inicialmente reescrever o nosso sistema representando o sistema na forma matricial: $ A.X = B $, onde $A$ é matriz de coeficientes, $X$ é o vetor de incógnitas e $B$ é o vetor dos
termos independentes de $X$.
    

Antes de passarmos os nossos dados do problema acima para o formato matricial usando arrays, comentaremos
algo mais sobre NumPy. Essa biblioteca é baseada nos métodos e rotinas de álgebra linear (LA) das famosas
bibliotecas numéricas conhecidas pelos nomes em inglês de LAPACK e BLAS. 

Portanto, NumPy possuem funções específicas para se resolver problemas ligados à álgebra, tais como sistemas lineares, determinantes,
auto-vetores, auto-valores, etc. Provavelmente num curso de cálculo numérico seu professor vai explorar
algumas técnicas, como, por exemplo, o método da eliminação de Gauss-Jordan, dentre outros.

A referência para a biblioteca NumPy, pode ser encontrada aqui: https://bit.ly/3qx1kwv e especificamente a 
discussão da biblioteca com funções de álgebra linear está em: https://bit.ly/3mJUKlh. Para relembrar ou
simplesmente rever o básico da teoria de sistemas lineares acesse: https://bit.ly/3ePqKQR.

### Usando NumPy para resolver sistemas lineares ###

No nosso sistema de exemplo, temos três incógnitas e três equações. Vamos organizar nossos dados em arrays, ou
seja vamos formatar $ X = A^{-1} * B $. Para ter certeza da solubilidade de A (pois A deve possuir inversa), vamos checar seu determinante e em seguida (sendo A inversível) obter a solução do sistema.

In [ ]:
# resolvendo o sistema do exemplo dado
import numpy as np
mtA = np.array([[3,2,1],[-2,3,3],[-1,2,-4]])
mtB = np.array([11, -19, -15])

In [ ]:
# Checando a matriz de coeficientes
print(mtA)


[[ 3  2  1]
 [-2  3  3]
 [-1 -3 -4]]


In [ ]:
# Checando o vetor coluna com os termos independentes das variáveis x
print(mtB)

[ 11 -19 -15]


In [ ]:
# chamando os métodos em linalg, para verificar o determinate de mtA
print(np.linalg.det(mtA))

-77.00000000000001


In [ ]:
# logo, vamos obter a solução do sistema com
print(np.round(np.linalg.solve(mtA,mtB),2))

[ 5.62 -3.29  0.7 ]


Observe que na solução acima chamamos o método de cálculo do determinante dado por 'np.linalg.det()' aplicado 
na matriz mtA. Em seguida usamos outro método numérico para resolver o sistema dado por np.linalg.solve() que
tomou como argumentos as matrizes mtA e mtB. 

Uma novidade é o método de arrendodamento que não foi o 'round' puro do Python, mas o 'np.round' próprio para
os arrays de NumPy, porque os objetos de NumPy são do tipo 'ndrarray' como já vimos, não suportados pelo 
método 'round' nativo do Python.

### Descobrindo mais sobre a NumPy ###
E por falar em matrizes inversas, determinantes e objetos matemáticos associados que tal avançar um pouco mais
na biblioteca de álgebra linear do NumPy. Vejamos os códigos a seguir...

In [ ]:
# Como criar matrizes identidades? veja o código abaixo...
MI =np.identity(5)   # matriz identidade de ordem 3
print(MI)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
# se mtA possui uma inversa qual é essa matriz?
inv_mtA = np.linalg.inv(mtA)
print(inv_mtA)

[[ 0.23376623 -0.12987013 -0.03896104]
 [ 0.14285714  0.14285714  0.14285714]
 [ 0.01298701  0.1038961  -0.16883117]]


In [ ]:
# arrendondando, temos ...
np.round(inv_mtA,2)

array([[ 0.14, -0.23, -0.14],
       [ 0.5 ,  0.5 ,  0.5 ],
       [-0.41, -0.32, -0.59]])

In [ ]:
# quero conferir as dimensões da matriz mtA, como faço
print(mtA.shape)

(3, 3)


In [ ]:
# e para mtB?
print(mtB.shape)

(3,)


In [ ]:
# Como fazer o produto de duas matrizes?

mt1 = np.array([[2,4],[1,1]])
mt2 = np.array([1,0])
# visualizando as matrizes definidas
print(mt1)
print(mt2)
# números de linhas e colunas
print(mt1.shape)
print(mt2.shape)
# fazendo o produto de ambas ...


[[2 4]
 [1 1]]
[1 0]
(2, 2)
(2,)


In [ ]:
# o produto com o método matmul do numpy...
res=np.matmul(mt1,mt2)
print(res)

[2 1]


Tanto em álgebra linear como em geometria analítica calcular o produto interno entre vetores é uma aplicação
bastante frequente. Vejamos como podemos resolver isso com 'numpy'...

In [ ]:
# produto interno entre vetores uv1 e uv2 ...
uv1 = [1,1,-1]
uv2 = [1,0,1]
prodUV = np.dot(uv1,uv2)
print(prodUV)

0


In [ ]:
dx = np.pi
xvar = np.arange(-dx/2, dx/2, 0.5)
print(xvar)

[-1.57079633 -1.07079633 -0.57079633 -0.07079633  0.42920367  0.92920367
  1.42920367]


Da mesma forma, também podemos utilizar uma função do numpy para calcular o produto vetorial entre dois vetores
dados, vejamos como:

In [ ]:
xUVvetor = np.cross(uv1,uv2)
print(xUVvetor)

[ 1 -2 -1]


A biblioteca de álgebra linear é vasta de métodos para calcular propriedades de matrizes e vetores, a referência
da biblioteca pode ser encontrada em: https://numpy.org/doc/stable/reference/routines.linalg.html, outra referência complementar para o assunto estudado é a https://numpy.org/doc/stable/reference/routines.matlib.html
que discute matrizes dentro da biblioteca numpy, especificamente.